export const dashboardPalette = {
  techBlue: '#286CFF',
  techBlueLight: '#E7F5FF',
  seaBlue: '#00ABEB',
  aeGreen: '#4A9D5C',
  aeGreenLight: '#F3FAF4',
  aeRed: '#EA4F49',
  aeRedLight: '#FEF2F2',
  aeGold: '#B68A35',
  aeGoldLight: '#F9F7ED',
  camelYellow: '#F29F0E',
  camelYellowLight: '#FFFBEB',
  desertOrange: '#EB5F24',
  desertOrangeLight: '#FEF5EE',
  slate: '#64748B',
  slateLight: '#F8FAFC',
  slateBorder: '#E2E8F0',
  pipelineBlue: '#5EAEEF',
  pipelineCyan: '#4FCBEF',
  pipelineYellow: '#E6C13F',
  pipelineOrange: '#E39563',
  pipelinePink: '#D98CE8',
  pipelineSlate: '#AEBBCC',
  chartBlue: '#2563A6',
  chartCyan: '#1597B8',
  chartYellow: '#C89B15',
  chartOrange: '#C9733D',
  chartPink: '#B660C5',
  chartSlate: '#64748B',
} as const

export const dashboardStatusColors = {
  approved: dashboardPalette.pipelineBlue,
  withReviewer: dashboardPalette.pipelineCyan,
  withApprover: dashboardPalette.pipelineYellow,
  clarification: dashboardPalette.pipelineOrange,
  needsWork: dashboardPalette.pipelinePink,
  drafted: dashboardPalette.pipelineSlate,
  reviewed: dashboardPalette.pipelineBlue,
  toReview: dashboardPalette.pipelineCyan,
  clarificationPending: dashboardPalette.pipelineOrange,
} as const
